<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Google dot com_deleteBtn</name>
   <tag></tag>
   <elementGuidId>5bbe6d2b-fa83-4585-9c1d-af3ac8235b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deleteBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='deleteBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#deleteBtn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e6b7bbfa-cea3-4dfb-a359-976c0f1db50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deleteBtn</value>
      <webElementGuid>5eeb939f-e84d-4fb0-8254-cae6670e2ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngbtooltip</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>60bf54c8-a704-475f-b8b1-7630f6496b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-outline-light</value>
      <webElementGuid>23cddfff-10b1-4e4d-8932-e36fc101c09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-tooltip-61</value>
      <webElementGuid>cb10470a-a856-474b-932f-208b84de4d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deleteBtn&quot;)</value>
      <webElementGuid>9eeee0b0-9f19-40e7-ac91-ef76b4665082</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='deleteBtn']</value>
      <webElementGuid>e82cbb38-e128-498f-b75f-de439257b8c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overlay-action-35']/div[2]/button[2]</value>
      <webElementGuid>6d6afa3f-5adc-4f26-ba1f-5c62542eb4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google dot com'])[1]/following::button[2]</value>
      <webElementGuid>0d4a44fd-3031-4961-86bf-2c97d961fc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ini gambar orang'])[1]/following::button[2]</value>
      <webElementGuid>52c5301a-4eed-471a-9b76-60f04b33fa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::button[1]</value>
      <webElementGuid>62608496-7b88-46c9-b25f-e5a76e82fe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 20 of 26 entries'])[1]/preceding::button[1]</value>
      <webElementGuid>d332cc75-44be-45a8-bb9d-866b2637e546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>085e8362-e807-499e-96de-cb4e86b28221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deleteBtn']</value>
      <webElementGuid>dc7e1600-0a22-4924-9f34-4a6428d694af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
