<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>e5b784ee-bb6a-432c-b8ca-ecb914fd72ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;thumbnail&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='thumbnail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;thumbnail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c02b2f31-07b0-4dea-ab21-3718e90b97fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>thumbnail</value>
      <webElementGuid>417db535-a0a2-48ad-8ec3-38521bbf74f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mvrcks-cms-api.venturo.pro/storage/mav-prod-resized/480x/ori/master/2025/4/11/1744362174.webp</value>
      <webElementGuid>11517e99-a90b-4d15-a928-53833bbc5d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/app-form-image[1]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row align-items-center mb-3&quot;]/div[@class=&quot;col-md-9&quot;]/app-modal-upload-image[1]/div[@class=&quot;upload-image-container&quot;]/div[@class=&quot;image-picker&quot;]/div[@class=&quot;image-ready&quot;]/img[1]</value>
      <webElementGuid>23e32ed7-09ec-4f6f-950e-1c4f339b7b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='thumbnail']</value>
      <webElementGuid>63653627-1e48-4ae9-b4af-e309ec910b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>28fae852-ed1d-47b7-8a7c-ba653e61411c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'thumbnail' and @src = 'https://mvrcks-cms-api.venturo.pro/storage/mav-prod-resized/480x/ori/master/2025/4/11/1744362174.webp']</value>
      <webElementGuid>87064e4c-2a12-441d-a0b0-00c238419e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
