<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Copyright Gambar_copyright</name>
   <tag></tag>
   <elementGuidId>d38ad0ca-953b-4819-b1ee-1e2d33ae9a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#copyright</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='copyright']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Isikan Copyright Gambar...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22e59f83-2861-4b3a-98fd-ece33afc40be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>copyright</value>
      <webElementGuid>9f03bba0-aa75-4862-8bd5-25501155302f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50cd59b6-d1e5-48d8-a6b1-186b8812ad06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>copyright</value>
      <webElementGuid>b8c8a188-33db-45dd-b571-1646e59a3397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan Copyright Gambar...</value>
      <webElementGuid>d343e053-b880-4f2e-ae6c-7eb374c58f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d5865eed-d6a5-4055-8cdf-de9730a47e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copyright&quot;)</value>
      <webElementGuid>e1bed5f9-75a3-46bb-9ed1-375c816d4303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='copyright']</value>
      <webElementGuid>0af81b46-2540-4ee4-a6d2-67ea2c667a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d25ce55f-c9a1-4b4c-9489-9428741734a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'copyright' and @type = 'text' and @name = 'copyright' and @placeholder = 'Isikan Copyright Gambar...']</value>
      <webElementGuid>1c491291-5ec9-4341-a0a9-a1285365600a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
