<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kategori</name>
   <tag></tag>
   <elementGuidId>93ed37c3-da83-4c38-8111-59fd87aec184</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='topnav-kategori']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ms-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fe80a85a-6497-4820-a460-2cd0b5392100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>cf047bf4-658c-4601-8a60-aa290f7ac713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori</value>
      <webElementGuid>bac99226-c20f-4ae4-9020-94e75a174944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-kategori&quot;)/span[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>88771cbb-f277-453f-a09a-3f88a97fe4e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='topnav-kategori']/span</value>
      <webElementGuid>ed22678e-a302-4e24-a4ac-98ad50999a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::span[1]</value>
      <webElementGuid>e9309a8f-df8e-4dac-a80a-16f4b3cbd2fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag'])[1]/following::span[1]</value>
      <webElementGuid>30e080d7-74de-45d1-8bb9-7ae6808f9a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Gambar'])[1]/preceding::span[1]</value>
      <webElementGuid>59bc8caf-efd8-459f-8048-16a35f55f8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[1]/preceding::span[2]</value>
      <webElementGuid>6bf12ec3-9d17-42f1-8780-74cf5cb2145c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>202c7832-3c29-4441-b4b6-0bb679de6895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kategori' or . = 'Kategori')]</value>
      <webElementGuid>3b1e0f4e-4708-4ce4-b938-5ccbbdb2ce4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
