<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_user_auto2gmail.com_editBtn</name>
   <tag></tag>
   <elementGuidId>dfcd6e2c-b5f0-4ff0-bd34-1dd1820fb26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(6) > td.vertical-middle.text-right > div.d-flex.justify-content-center.align-items-center.column-gap-2 > #editBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='editBtn'])[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7e06a8b-1b7a-43d2-935c-6bd1a3a952e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editBtn</value>
      <webElementGuid>d47f7c78-315b-4d29-a58c-c160a5d2c8e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngbtooltip</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>dd31ffc4-ecd7-401a-b2c3-25f863bd878d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-outline-primary</value>
      <webElementGuid>41bd41d1-b846-430c-bb93-666024b01164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-tooltip-76</value>
      <webElementGuid>32c32f6d-ebff-4a9b-9896-cf604d074177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DataTables_Table_1&quot;)/tbody[1]/tr[6]/td[@class=&quot;vertical-middle text-right&quot;]/div[@class=&quot;d-flex justify-content-center align-items-center column-gap-2&quot;]/button[@id=&quot;editBtn&quot;]</value>
      <webElementGuid>eb23ffbf-0522-461b-a6ce-fd6c431b993f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='editBtn'])[6]</value>
      <webElementGuid>ebd9f0ce-8f69-4dd5-98d6-56248cc560f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='DataTables_Table_1']/tbody/tr[6]/td[4]/div/button[2]</value>
      <webElementGuid>e164bc61-33c3-49ba-9997-4d1cbbd02efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user_auto2@gmail.com'])[1]/following::button[2]</value>
      <webElementGuid>363dbbf9-87bb-4bd2-91f6-600a86ed1216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user auto2'])[1]/following::button[2]</value>
      <webElementGuid>c2170afd-b501-42da-b7cb-bc7486c34ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>c2bc7ee4-65d8-4e50-b290-a54447c332dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='user auto'])[1]/preceding::button[2]</value>
      <webElementGuid>f61cc033-a5a9-4c0e-b1fb-ab155fe2af61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/div/button[2]</value>
      <webElementGuid>78bb1aba-2092-4789-a377-612ce3eb9de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'editBtn']</value>
      <webElementGuid>f72d04a4-1a7d-4d3d-8386-97d0c3a4d7a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
