<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Google_editBtn</name>
   <tag></tag>
   <elementGuidId>a60d61d4-0a8d-45f9-9c42-6707ffda5266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;editBtn&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overlay-action-35 > div:nth-of-type(2) > #editBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#overlay-action-35 #editBtn</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9e6eb58f-0086-4ad6-b769-460cf9d8817f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>editBtn</value>
      <webElementGuid>99300499-3972-44ee-af1e-4e635b792c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ngbtooltip</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>92f06b15-3ab4-4ab1-b0f5-c08dcd310c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-outline-light</value>
      <webElementGuid>1e2bb865-aca0-4dce-a95b-8752d626f35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>ngb-tooltip-66</value>
      <webElementGuid>b93e4417-417c-476f-a920-c295be184265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay-action-35&quot;)/div[2]/button[@id=&quot;editBtn&quot;]</value>
      <webElementGuid>e66f3ff7-9fe8-4099-9bf3-d5a555aa9459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='editBtn'])[4]</value>
      <webElementGuid>dcb2d510-a0ed-458e-a196-e08c2576496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overlay-action-35']/div[2]/button</value>
      <webElementGuid>117b9299-2676-4ef4-9d3a-04d728b44da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[4]/following::button[1]</value>
      <webElementGuid>541de52f-9ffc-4ca3-b104-622cf21a19b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ini gambar'])[4]/following::button[1]</value>
      <webElementGuid>d1ad5985-23a7-4d72-82b3-2d35fc80d43a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::button[1]</value>
      <webElementGuid>b7368f0d-f573-4fa1-8c22-4bf62c465aa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Showing 1 to 20 of 29 entries'])[1]/preceding::button[2]</value>
      <webElementGuid>049bc777-7d16-4dcb-8bd6-fc80678108fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/div/div/div[2]/button</value>
      <webElementGuid>caaf9305-9de3-43f9-8ea6-a5db775222dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'editBtn']</value>
      <webElementGuid>b5ae68b2-c543-425c-b3d2-ff58997c36d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
