<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ini gambarGoogle</name>
   <tag></tag>
   <elementGuidId>4d3a2467-fe0e-4e96-9ce8-e2241bc51cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;layout-wrapper&quot;]/div/div/div[2]/div/app-list-image/div/div/div/div/div[2]/div/div[1]/div[1]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overlay-action-34</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#overlay-action-34</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>329ad8af-de79-4339-bfa9-8f630a8a2aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overlay-action-34</value>
      <webElementGuid>fac6d8f9-9edf-473d-8d03-f472a2f9fd09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bankImageItemSelected</value>
      <webElementGuid>2578dbfd-8554-404f-bae3-e157bde59eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ini gambarGoogle</value>
      <webElementGuid>586a670f-4d95-4fda-9ec6-1343bb595053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay-action-34&quot;)</value>
      <webElementGuid>d33bd9ea-d0b2-4eeb-8433-6b2ea3f008ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='overlay-action-34']</value>
      <webElementGuid>95ca44fb-5341-4c71-b64f-a01be6a32d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div/div/div[2]/div/app-list-image/div/div/div/div/div[2]/div/div/div[3]/div/label/div/div</value>
      <webElementGuid>5c4e3d89-8200-46bb-956a-50bcffe7a6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Google'])[2]/following::div[5]</value>
      <webElementGuid>1882f57a-840b-4bf0-b5b9-ddb66fc6d1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ini gambar'])[2]/following::div[5]</value>
      <webElementGuid>bf2d7680-bfb1-4430-9293-22e772ff76e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/label/div/div</value>
      <webElementGuid>6b9d779b-1565-4a7a-8c92-feb1ba290f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'overlay-action-34' and (text() = 'ini gambarGoogle' or . = 'ini gambarGoogle')]</value>
      <webElementGuid>5b93d368-5f83-45c9-b13c-cacaf3ab298a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
