<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>1ca2d512-a967-41f1-9a0e-e238702b9240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/ngb-modal-window/div/div/div[2]/app-form-image/form/div/div/div/div/div[1]/div/div[3]/div/app-modal-upload-image/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;thumbnail&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;thumbnail&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4394343a-d61c-490b-ae3d-7579cc6629e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>thumbnail</value>
      <webElementGuid>4d4cb73c-fe79-4a2f-99c9-6c517356abc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mvrcks-cms-api.venturo.pro/storage/mav-prod-resized/480x/ori/master/2025/4/11/1744353389.webp</value>
      <webElementGuid>c51b6a38-7082-4285-baf4-3ac5fa8ba612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/app-form-image[1]/form[@class=&quot;ng-valid ng-dirty ng-touched&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row align-items-center mb-3&quot;]/div[@class=&quot;col-md-9&quot;]/app-modal-upload-image[1]/div[@class=&quot;upload-image-container&quot;]/div[@class=&quot;image-picker&quot;]/div[@class=&quot;image-ready&quot;]/img[1]</value>
      <webElementGuid>62981782-4771-4f07-ad42-1caeda7e7897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='thumbnail']</value>
      <webElementGuid>5bc0a87a-6402-46f3-b2e7-3b80bdbe6ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>6145902e-1968-4e4e-8640-fc03fd3a9402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'thumbnail' and @src = 'https://mvrcks-cms-api.venturo.pro/storage/mav-prod-resized/480x/ori/master/2025/4/11/1744353389.webp']</value>
      <webElementGuid>088e83aa-2d27-4268-98df-0e7c90bc828d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
