<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Caption Gambar_template_param_key_ima_14b451</name>
   <tag></tag>
   <elementGuidId>9bda74a9-f6db-4310-b382-e1fba31af57c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=' template_param_key_image_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Isikan Caption...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83a34119-12d5-44f0-963f-b2ae4c1b217a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a109c354-2d2b-4f87-a605-27a885ff2530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value> template_param_key_image_description</value>
      <webElementGuid>f186faea-ba11-4744-90a3-149e4ad87e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>template_param_key_image_description</value>
      <webElementGuid>c9a497a7-f165-4e94-ad94-6a69935619ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan Caption...</value>
      <webElementGuid>12c60ec6-42c0-4b47-bac5-f8f140c48380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>0d56ade1-75ba-4c9d-b8fc-06ebb66866fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot; template_param_key_image_description&quot;)</value>
      <webElementGuid>f4e61a44-9df8-4835-b03d-e9bb4de06ee6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id=' template_param_key_image_description']</value>
      <webElementGuid>7c256de5-4548-4999-936c-e11a9cc046fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newsForm']/div/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>aa068c1c-fb95-4318-a0c5-c74b1f59cf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>a2d4d845-9d22-4e06-aa6d-7e90fb717826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = ' template_param_key_image_description' and @name = 'template_param_key_image_description' and @placeholder = 'Isikan Caption...']</value>
      <webElementGuid>a98a7208-b166-4c5b-b6c5-fe3808c41d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
