<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kategori</name>
   <tag></tag>
   <elementGuidId>934cc345-a9ef-448d-808a-898cbc3b296d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ms-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='topnav-kategori']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ba417514-8676-4519-8389-986d453bcf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-2</value>
      <webElementGuid>86175c4e-40c7-477e-9d3e-8abe1a7fb736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kategori</value>
      <webElementGuid>3e7d2fb1-ec94-44b9-829d-1fe4df6de307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;topnav-kategori&quot;)/span[@class=&quot;ms-2&quot;]</value>
      <webElementGuid>cb6ec2b0-4c18-477b-98a5-d405d11bf0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='topnav-kategori']/span</value>
      <webElementGuid>1a7a82d5-cec5-4cfb-b19e-1fe18fbfa214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::span[1]</value>
      <webElementGuid>523a4014-879e-4844-9ee7-92d2bec8a3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tag'])[1]/following::span[1]</value>
      <webElementGuid>6eb5b952-47a6-4af4-a757-15ad8ef16fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Gambar'])[1]/preceding::span[1]</value>
      <webElementGuid>9fe9f9ac-a614-4a03-96d9-2848d6c4e07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[1]/preceding::span[2]</value>
      <webElementGuid>9d7d7b24-7ab6-4c6c-9221-35bc461454b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>ad5a8bb2-22c4-4005-99d0-bdc593c6387a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Kategori' or . = 'Kategori')]</value>
      <webElementGuid>42dcb2be-143e-458e-abbb-4b76ff4b85d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
