<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__template_param_key_image_copyright</name>
   <tag></tag>
   <elementGuidId>3888aab6-8f07-4aac-92ac-c37f7d60cb71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='template_param_key_image_copyright']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#template_param_key_image_copyright</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Isikan copyright gambar...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc586386-a7a8-4fd3-821c-c7775f1f4e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>056f5e78-2e6a-491f-abf0-37be629da02f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>template_param_key_image_copyright</value>
      <webElementGuid>767209ea-2f6c-4b0e-b01a-fd17656a7e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>template_param_key_image_copyright</value>
      <webElementGuid>1f102fe4-09df-4efd-a6aa-bfa8ae314494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan copyright gambar...</value>
      <webElementGuid>5bf80954-ca8c-4695-88b3-dc6338bb4062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5bb82280-f2b9-45e3-bdaa-9eef3933e042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template_param_key_image_copyright&quot;)</value>
      <webElementGuid>dcc731c7-76a4-49e7-af10-0bf2c68d6eaa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='template_param_key_image_copyright']</value>
      <webElementGuid>410919f5-6749-4db6-934a-7afcd4477ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newsForm']/div/div/div/div[2]/div[4]/div[2]/div/input</value>
      <webElementGuid>02a0f150-7f89-46f5-8e37-52d6dcb63b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>a1b36be0-e7f3-4b4d-b244-c9b6d4941f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'template_param_key_image_copyright' and @name = 'template_param_key_image_copyright' and @placeholder = 'Isikan copyright gambar...']</value>
      <webElementGuid>523142e5-c7e1-48d9-a138-37f3b500be88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
