<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__template_param_key_image_copyright</name>
   <tag></tag>
   <elementGuidId>dc8250bf-b942-4bdc-ac88-fc6190c5d11d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#template_param_key_image_copyright</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='template_param_key_image_copyright']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Isikan copyright gambar...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e8ebe807-2c14-4141-b729-162ee4665b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0dab2361-1bcf-44c9-b04f-3ebbaf885f57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>template_param_key_image_copyright</value>
      <webElementGuid>11a9eac6-74ed-425a-8388-031c7bf02a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>template_param_key_image_copyright</value>
      <webElementGuid>eb3530c4-7af7-46d0-87e6-b6fbbd37934c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Isikan copyright gambar...</value>
      <webElementGuid>362bcad6-38a8-42da-8f5e-8c8d32c94df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>e1ddc6c2-935c-4802-ae28-75297465e5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template_param_key_image_copyright&quot;)</value>
      <webElementGuid>3a1d6e63-c835-4be3-913b-48b8c18cbe38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='template_param_key_image_copyright']</value>
      <webElementGuid>c67c526d-735a-4b08-98c8-d4032e3a5859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='newsForm']/div/div/div/div[2]/div[4]/div[2]/div/input</value>
      <webElementGuid>45c42916-4eba-4bc6-b957-6817232fbf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>43db60d8-1b31-4a80-8c71-90a85cea90bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'template_param_key_image_copyright' and @name = 'template_param_key_image_copyright' and @placeholder = 'Isikan copyright gambar...']</value>
      <webElementGuid>2aa16277-797d-433e-9ea8-12dcc9d63b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
