<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Pilih tipe konten --  Trending  Timeless</name>
   <tag></tag>
   <elementGuidId>9009c6ed-9e53-477d-999e-10ee462f1d80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;content_type&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='content_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7dbfaff1-6afc-494f-81e1-ed1186bc7ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>content_type</value>
      <webElementGuid>58eb58c9-1aa7-4c0b-9111-ccbdab14c7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm bg-white ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b15bbac6-0a8d-4df0-a118-1533265e505f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    -- Pilih tipe konten --     Trending     Timeless </value>
      <webElementGuid>d1924eb1-32e5-4b8c-9701-75f341525aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content_type&quot;)/div[@class=&quot;card card-body py-0&quot;]/div[@class=&quot;custom-select&quot;]/select[@class=&quot;form-control form-control-sm bg-white ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>262c7d61-80eb-45de-b0e9-a06ee8c3baac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='content_type']</value>
      <webElementGuid>e2b65e1d-7fd9-49ff-b425-d087948863d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_type']/div/div/select</value>
      <webElementGuid>5a2ce8f2-fbc1-4b18-923c-16240911287c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tipe konten'])[1]/following::select[1]</value>
      <webElementGuid>868a3483-2470-4d5c-830f-246ad25ed530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kategori'])[1]/following::select[2]</value>
      <webElementGuid>19ebd9f8-284b-4d65-b955-7f7f955e689a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Homepage Pick'])[1]/preceding::select[1]</value>
      <webElementGuid>b187b96b-5a0b-4822-a99b-18ddb3352b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan artikel di Home'])[1]/preceding::select[1]</value>
      <webElementGuid>df323800-4480-4f63-bfa1-a7b38f5c4baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/select</value>
      <webElementGuid>f7e5c3d3-871e-416e-b239-23e74d89fef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'content_type' and (text() = '    -- Pilih tipe konten --     Trending     Timeless ' or . = '    -- Pilih tipe konten --     Trending     Timeless ')]</value>
      <webElementGuid>d61d1aa0-0425-43ad-a369-8a3438c20e23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
