<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_JampidsusJampidsus</name>
   <tag></tag>
   <elementGuidId>38c4f68d-afa7-4a49-9617-3745be0df409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overlay-action-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overlay-action-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;JampidsusJampidsus&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc26cb0e-6848-4241-8a68-d6e00a34faab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overlay-action-28</value>
      <webElementGuid>23a4959d-e066-4056-816d-5e420acdfb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bankImageItemSelected</value>
      <webElementGuid>59423948-14b5-4399-a990-765d92ddd753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>JampidsusJampidsus</value>
      <webElementGuid>dc47123b-0951-428b-bbf7-f914e1fdbac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlay-action-28&quot;)</value>
      <webElementGuid>d7e5f923-feb3-4d7e-8176-f3318b05498f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='overlay-action-28']</value>
      <webElementGuid>c4a6459c-9d87-45b2-a20a-e2a264eab694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Story Kejaksaan'])[1]/following::div[4]</value>
      <webElementGuid>f9791a2d-84cf-48f5-b2dc-00fa9735a147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guru Besar'])[1]/following::div[4]</value>
      <webElementGuid>88c74140-60dd-4617-b483-631c8f524e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/div/div</value>
      <webElementGuid>afa7e457-7eba-47b5-9409-7fecc0611eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'overlay-action-28' and (text() = 'JampidsusJampidsus' or . = 'JampidsusJampidsus')]</value>
      <webElementGuid>2a5e6368-27b5-4f30-a7e0-8c5e4415cce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
