<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ngb-modal-window_Pilih gambar header Local _9a3117</name>
   <tag></tag>
   <elementGuidId>32e34025-f09a-4351-beca-0aff4ae624fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='PM'])[1]/following::ngb-modal-window[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ngb-modal-window.d-block.modal.fade.show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ngb-modal-window</value>
      <webElementGuid>e7d159d9-2180-49d8-a188-c7b820d6a6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>64590926-ec62-4f05-9b4b-1b03d2baefb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d451430f-4454-4b95-8a1f-a4824efd57a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-modal</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32426101-2411-4638-bcdb-835580df9630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block modal fade show</value>
      <webElementGuid>a58f54d9-b897-460e-ac0c-98660b33c917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pilih gambar header Local - KomputerServer - Bank Image</value>
      <webElementGuid>e2259dc7-5578-4158-98ff-e3bca6016ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/ngb-modal-window[@class=&quot;d-block modal fade show&quot;]</value>
      <webElementGuid>0bf69ca5-dcb4-4cdd-8601-2cc1cceaa153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PM'])[1]/following::ngb-modal-window[1]</value>
      <webElementGuid>891f03bc-9d3c-4a1c-aa9c-366c586ca558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[1]/following::ngb-modal-window[1]</value>
      <webElementGuid>670e7b33-6338-4b82-a898-190d0067d127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ngb-modal-window</value>
      <webElementGuid>59508b4d-3abc-425c-9103-bb72595bdff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ngb-modal-window[(text() = ' Pilih gambar header Local - KomputerServer - Bank Image' or . = ' Pilih gambar header Local - KomputerServer - Bank Image')]</value>
      <webElementGuid>2532a97e-a9ef-4512-a7df-350ce04c5eda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
